### ISSUE TITLE
getTimeoutMinutes() shall return an integer value?

### ISSUE THREAD

**Issue by drfho** [zopefoundation/Products.Sessions#17]
https://github.com/zopefoundation/Products.Sessions/blob/a756218d05eb2403c252b89664f46157ac2f25b2/src/Products/Transience/Transience.py#L924

Hello,
now(?) _getTimeoutMinutes()_  provides a **float**-type, but the ZMI template
https://github.com/zopefoundation/Products.Sessions/blob/a756218d05eb2403c252b89664f46157ac2f25b2/src/Products/Transience/dtml/manageTransientObjectContainer.dtml#L44-L45
requires an **integer**-type. Thus the form values of  _Transient Object Container_ cannot be saved anymore, if on any change the "Timeout" value is not explicitly set to an integer value. We could fix it via ZMI template code:
`-  value="<dtml-var name="getTimeoutMinutes" html_quote>" />`
`+ value="<dtml-var expr="int(getTimeoutMinutes())">" />`

Other ideas?
Best regards
fh

**Comment by icemac** [comment]
I suggest to change the implementation of `getTimeoutMinutes()` from

https://github.com/zopefoundation/Products.Sessions/blob/a756218d05eb2403c252b89664f46157ac2f25b2/src/Products/Transience/Transience.py#L924-L926

to 

```python
return self._timeout_secs // 60
```

This works both on Python 2 and 3 and always returns `int` values.

A pull request is welcome.
