### ISSUE TITLE
Quick ZMI layout fix

### ISSUE THREAD

**Issue by drfho** [zopefoundation/Products.Sessions#18]
https://github.com/zopefoundation/Products.Sessions/blob/a756218d05eb2403c252b89664f46157ac2f25b2/src/Products/Sessions/dtml/manageDataManager.dtml#L3-L5

Hello,
If the two lines are reversed the ZMI layout gets correct:
`3  <dtml-var "manage_tabs(this(), _, form_title='Manage Session Data Manager')">`
`4`
`5  <main class="container-fluid">`

Best 
fh

**Comment by icemac** [comment]
A pull request is welcome.
