### ISSUE TITLE
Not compatible with ZODB/ZEO 5.0

### ISSUE THREAD

**Issue by hannosch** [zopefoundation/Products.Sessions#2]
There are import errors resulting in test failures with ZODB/ZEO 5.0.

**Comment by mauritsvanrees** [comment]
The import errors are gone.  Plone 5.2 (in development) is using `Products.Sessions 4.0` and ZODB 5.
Your commit 01e41f41102e5bfd2c3edb1e8a2d8ca486bdaa6b fixed it, and made the tests use ZODB/ZEO 5 again. Seems we can close this one.
