### ISSUE TITLE
TransientObject does not implement __contains__

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.Sessions#21]
[Products.Transience.TransientObject.TransientObject](https://github.com/zopefoundation/Products.Sessions/blob/master/src/Products/Transience/TransientObject.py#L63) only implements `has_key` but not `__contains__`.

**Comment by jamadden** [comment]
The `DictionaryLike` interface it implements [doesn't specify `__contains__`](https://github.com/zopefoundation/Products.Sessions/blob/master/src/Products/Transience/TransienceInterfaces.py#L136).

**Comment by icemac** [comment]
It would be nice to have it in the interface, too, as `has_key` smells like Python 2 only and `2to3` converts each `has_key` into code using `__contains__`.

**Comment by dataflake** [comment]
Keep in mind that this is not the only session implementation out there. If you were to add `__contains__` here and start using it outside of this particular package that would most likely immediately break other implementations.

**Comment by icemac** [comment]
@dataflake  Hm, I was not aware of this fact. At least would it be easy to detect whether another implementation can be used together with code which expects `TransientObject` or `DictionaryLike` to implement `__contains__`: It will break with an `AttributeError` (which can be hidden via a `try except` statement `*sigh*`).

**Comment by dataflake** [comment]
@icemac so for right now both `has_key` and `__contains__` work on `TransientObject`. What "consumers" do is up to them. But they need to be careful if they blindly epect `__contains__` to work on third-party implementations.
