### ISSUE TITLE
No longer recommend tempstorage

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.Sessions#26]
Tempstorage is broken and cannot be used with Python 3.
No longer suggest to use in the documentation.

_Originally posted by @d-maurer in https://github.com/zopefoundation/Products.Sessions/issues/4#issuecomment-513474739_

See also the suggestions to use a normal storage in #4.

**Comment by icemac** [comment]
Additionally the dependency on `Products.TemporaryFolder` is only used in the tests, it shouldn't be an installation dependency of this package. (`Products.TemporaryFolder` needs `tempstorage` to run.)

**Comment by dataflake** [comment]
@icemac I have added additional documentation in the README in 06f6c28a41c35e294939eab14940678e43c89cad and moved the dependency on `Products.TemporaryFolder` into a `tests` extra in 08d07e54fc831f62bd851194236002e040dd8a90. Let me know if this is enough to address this issue so I can create a release (see #29)

**Comment by mauritsvanrees** [comment]
Those changes seem good to me.

For the record, currently Plone has the TemporaryFolder in its [dependencies](https://github.com/plone/Products.CMFPlone/blob/5.2.0/setup.py#L111). Plone should probably remove that. I will create an issue for that.

**Comment by dataflake** [comment]
OK, I went ahead and made the release. I believe the issues raised here are addressed.

**Comment by icemac** [comment]
@dataflake LGTM.
