### ISSUE TITLE
Include linting for Travis

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Products.Sessions#27]
The tox-env "lint-py37" is currently broken, but nobody noticed, as Travis does not run it.

**Comment by jugmac00** [comment]
I could use a helping hand here.

With PR #28 I tried to run the linter on Travis - which passes - but I expected it to fail, as `tox -e=lint-py37` fails for me locally.

I have not yet incorporated the fix to the broken noqa syntax.

**Comment by dataflake** [comment]
The linting issues and Travis configuration are now fixed on master.
