### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/Products.Sessions#29]
A new release would be appreciated, to be included in a Plone 5.2.1 release before the Plone conference starts.

**Comment by dataflake** [comment]
I'll look at that today and want to fix #26 before making the release.

**Comment by dataflake** [comment]
@mauritsvanrees Just waiting for feedback from @icemac on #26 before making the release.

**Comment by dataflake** [comment]
Release 4.6 is now online.
